frontend:
  dpname: myapp
  image:
    frepository: 888229101819.dkr.ecr.ap-south-1.amazonaws.com/expimg:5088fdb
    tagg: 5088fdb
    pullPolicy: Always
  replicaCount: 1

mongo:
  name : mongo
  image:
    repository: mongo
    tag: latest
  replicaCount: 1

server:
  dpname: server
  image:
    brepository: 888229101819.dkr.ecr.ap-south-1.amazonaws.com/expimg-back:5088fdb
    tagb: 5088fdb
    pullPolicy: Always
  replicaCount: 1

myappService:
  ports:
    port: 80
    targetPort: 3000
  type: NodePort  

mongoService:
  ports:
    port: 27017
    targetPort: 27017
  type: LoadBalancer  

serverService:
  ports:
    port: 80
    targetPort: 4000
  type: NodePort  

serverHPA:
  name: myexp-autoscaler
  scaleTargetRefKind: Deployment
  scaleTargetRefName: server
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

persistentVolume:
  name: myexp-pv
  capacity: 250Mi
  volumePath: "/temp/data"
  storageClassName: standard
  reclaimPolicy: Retain

persistentVolumeClaim:
  name: myexp-pvc
  storageRequest: 250Mi
  accessMode: ReadWriteOnce
  storageClassName: standard
