frontend:
  dpname: myapp
  image:
    repository: tharunika21/tggfinfrontendimage
    tag: latest
    pullPolicy: Always
  replicaCount: 1

mongo:
  name : mongo
  image:
    repository: mongo
    tag: latest
  replicaCount: 1

server:
  dpname: server
  image:
    repository: tharunika21/tggfinbackendimage
    tag: latest
    pullPolicy: Always
  replicaCount: 1

myappService:
  ports:
    port: 80
    targetPort: 3000
  type: NodePort  

mongoService:
  ports:
    port: 27017
    targetPort: 27017
  type: LoadBalancer  

serverService:
  ports:
    port: 80
    targetPort: 4000
  type: NodePort  

serverHPA:
  name: exp-autoscaler
  scaleTargetRefKind: Deployment
  scaleTargetRefName: server
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

persistentVolume:
  name: exp-pv
  capacity: 250Mi
  volumePath: "/temp/data"
  storageClassName: standard
  reclaimPolicy: Retain

persistentVolumeClaim:
  name: exp-pvc
  storageRequest: 250Mi
  accessMode: ReadWriteOnce
  storageClassName: standard
