{{- if .Values.frontend.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.dpname }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.frontend.image.frepository }}:{{ .Values.frontend.image.tagg }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 3000
{{- end }}
