apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.dpname }}
spec:
  selector:
    app: myapp
  ports:
    - port: {{ .Values.myappService.ports.port }}
      targetPort: {{ .Values.myappService.ports.targetPort }}
  type: {{ .Values.myappService.type }}
