apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessMode }}
  hostPath:
    path: {{ .Values.persistentVolume.volumePath }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
