{{- if .Values.server.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.dpname }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: "{{ .Values.server.image.brepository }}:{{ .Values.server.image.tagb }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
{{- end }}
