name: Update Helm Chart

on:
  # workflow_run:
  #   workflows: ["Build and Push Docker Images"]
  #   types:
  #     - completed
  workflow_dispatch:

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm Chart Repository
        uses: actions/checkout@v2
        with:
          repository: Tharunika-21/tharuni-helm  

      - name: Update Helm Chart Values
        run: |
          sed -i "s|repository: tharunika21/tggtaskexpfrontendimg|repository: ${{ github.event.inputs.image_repo_frontend }}|" ./values.yml
          sed -i "s|tagg: latest|tagg: ${{ github.event.inputs.image_tag_frontend }}|" ./values.yml
          sed -i "s|repository: tharunika21/tggtaskexpbackendimg|repository: ${{ github.event.inputs.image_repo_backend }}|" ./values.yml
          sed -i "s|tag: latest|tag: ${{ github.event.inputs.image_tag_backend }}|" ./values.yml
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "tharunika.cs20@bitsathy.ac.in"
          git config --local user.name "Tharunika-21"

          git add ./values.yaml
          git commit --allow-empty -m "Updated values.yml"
          git push origin main

        
